[package]
name = "graph-util"
version = "0.1.0"
authors = [ "Max Grübmeyer" ]
edition = "2021"

[dependencies]
regex = "1.11.1"
# TODO (GM): Remove this if it's not needed!
# once_cell = "1.20.2"

[[bin]]
name = "main"
path = "main.rs"
